name: coderco customer action

description: Greet someone

inputs:
  who-to-greet:
    description: The name of the person to greet
    required: true
    default: Hello

outputs:
  time:
    description: The current time

runs:
  using: node24
  main: dist/index.js
