name: coderco combined

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r chapter_4/requirements.txt

      - name: run tests
        run: |
          cd chapter_4
          python -m unittest discover

      - name: notify us success
        run: echo "Tests passed on Python 3.12"
        if: success()
