name: coderco custom action ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: hello world custom action
        uses: ./custom_actions
        with:
          who-to-greet: "coderco team"
